env:
  global:
    - CC_TEST_REPORTER_ID=ef623ee7366a025f6191b4255e27896dc5376e8223831e4b9c288238d3077825

language: php
php:
  - 7.2

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cd ..
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout 1.0.13
  - ./autogen.sh
  - ./configure
  - echo "Installing libsodium..."
  - sudo make install
  - cd ..
  - echo "Installing ext/sodium..."
  - pecl install libsodium
  - cd HomeKit

script:
  - phpdbg -qrr phpunit tests --configuration tests/phpunit.xml --coverage-clover clover.xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT