name: Tests

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Install latest PHPUnit
      run: wget https://phar.phpunit.de/phpunit.phar

    - name: Run Tests
      run: phpdbg -qrr phpunit.phar tests --configuration tests/phpunit.xml --coverage-clover clover.xml
